name: Terraform CI/CD for Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  provision:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [ dev, test, prod ]

    defaults:
      run:
        working-directory: environments/${{ matrix.env }}

    env:
      ARM_CLIENT_ID:       ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET:   ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
      ARM_TENANT_ID:       ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Select or Create Workspace
        run: terraform workspace select -or-create ${{ matrix.env }}

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' || matrix.env != 'prod'
        run: terraform apply -auto-approve
